### ISSUE TITLE
[map] to-do list

### ISSUE THREAD

**Issue by EPuncker** [EPuncker/orts2#25]
**Missing locations:**
- [ ] Heart of Despair/Dungeon of Despair (Tarbaz)
- [ ] Dungeon of Plague (Plagirath)
- [ ] Dungeon of Inferno (Mazoran)
- [ ] Dungeon of Damnation (Shulgrax)
- [ ] Dungeon of Destruction (Razzagorn)
- [ ] Dungeon of Deceit (Zamulosh)
- [ ] Dungeon of Decay (Ragiaz)
- [ ] Corym Black Market
- [ ] Water Elemental Dungeon
- [ ] Tainted Caves
- [ ] Kha'zeel Scarab Lair
- [ ] Mother of Scarabs Lair
- [ ] Forbidden Temple
- [ ] Nightmare Isles (Mini World Change)
- [ ] Hunter Camp/Dworc Camp (Mini World Change)
- [ ] Kha'zeel Dragon Lairs/Tiquanda

**Others:**
- [ ] Add guild hall depots to the ones that are missing
- [ ] Add free item crates (id 9661)
- [ ] Add entrance and exit to seacrest serpents (need to check youtube) Position(33545, 31859, 7)
- [ ] Add seacrest serpent to spawn (I don't know if they are regular spawn or triggered)
- [ ] Turn back the stair from Position(32888, 32081, 5) to ID 19510 and add a script to teleport to Position(32887, 32081, 4)
- [ ] Add message to all other stair 19510 on map to tell the player that he is not going to climb it (need to gather proper message)
- [ ] Add script for stony pound on Position(33264, 32015, 7) to teleport to dryads cave (and also a way out)
- [ ] Add PvP arenas/Monsters arenas and their entrances in the cities
- [ ] Add Grimvale NPCs
- [ ] Add vortices from: https://tibia.fandom.com/wiki/Updates/10.94#New_Features_and_Changes update

**Comment by omarcopires** [comment]
Is this list complete until update 10.98?

**Comment by EPuncker** [comment]
> Is this list complete until update 10.98?

now it is

**Comment by Wchoteheey** [comment]
any new updates ? :)

**Comment by Wchoteheey** [comment]
@EPuncker  can you explain all poionts better? I want to help but sometimes I don't understand what do you mean ex. "add guild hall depots to the ones that are missing" so.. where?

**Comment by omarcopires** [comment]
@Wchoteheey sorry I'm tagging you instead of replying to your comment, for some reason it's not working for me. This is the deposit boxes that are located inside the guild houses.

**Comment by Wchoteheey** [comment]
> sorry I'm tagging you instead of replying to your comment, for some reason it's not working for me. This is the deposit boxes that are located inside the guild houses.

No worry.
I understand now. But I see here a lot of uncomplete comments "to do" I want to know where is bug exactly.

**Comment by EPuncker** [comment]
not completed at all
